version: "3.5"
services:
  frontend:
    image: quay.io/krakaw/block-explorer-frontend:latest
    env_file: .env.docker.frontend
    volumes:
    - frontend:/app/dist
  api:
    image: quay.io/krakaw/blockchain-explorer-api:latest
    env_file: .env
    ports:
      - "4000:4000"
    restart: unless-stopped
    volumes:
      - frontend:/app/public
    depends_on:
      - tari
      - redis
      - frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 10s
      timeout: 5s
      retries: 3
  tari:
    image: quay.io/krakaw/tari_base_node:latest
    volumes:
      - "$PWD/_data/tari:/root/.tari"
      - "$PWD/scripts/docker-fix-config.sh:/usr/bin/docker-fix-config.sh"
    ports:
      - "18142:18142"
    stdin_open: true
    tty: true
    command:
      - "/usr/bin/docker-fix-config.sh"
      - "/usr/bin/start.sh"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - "$PWD/_data/redis:/data"
    command: "redis-server --appendonly yes"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  frontend:

